name: alarm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0
  tflite_flutter: ^0.10.4
  record: ^5.1.2
  path_provider: ^2.1.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/yamnet.tflite

dependency_overrides:
  record_linux: ^1.0.0